# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - cae-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     cache: npm
      #     cache-dependency-path: node_modules/.package-lock.json
      #     node-version: 16
      
      # - name: npm install and build
      #   run: |
      #     chmod 777 node_modules/.bin/vue-cli-service
      #     npm install
      #     npm run build
      
      # - name: npm install and build
      #   run: |
      #     chmod 777 node_modules/.bin/vue-cli-service
      #     npm install
      #     npm run build
      
      # - name: build images
      #   run: docker build -t cae-frontend:1.0.0 .

      # - name: Login to SWR
      #   run: docker login -u me-east-1@EEWKRHXE5OFSDHGB6LNZ -p ${{ secrets.docker_secret }} swr.me-east-1.myhuaweicloud.com

      # - name: Push to SWR
      #   run: |
      #     docker tag cae-frontend:1.0.0 swr.me-east-1.myhuaweicloud.com/demo-cae/cae-frontend:1.0.0
      #     docker push swr.me-east-1.myhuaweicloud.com/demo-cae/cae-frontend:1.0.0

      # 下载并安装华为云 CLI
      - name: Install HuaweiCloud CLI
        run: |
          curl -sSL https://cn-north-4-hdn-koocli.obs.cn-north-4.myhuaweicloud.com/cli/latest/hcloud_install.sh -o ./hcloud_install.sh && sudo bash ./hcloud_install.sh -y
          sudo hcloud --version

      # 配置华为云 CLI
      - name: Configure HuaweiCloud CLI
        run: |
          sudo hcloud configure --profile default --region me-east-1 --ak ${{ secrets.HUAWEICLOUD_AK }} --sk ${{ secrets.HUAWEICLOUD_SK }}
        env:
          HUAWEICLOUD_AK: EEWKRHXE5OFSDHGB6LNZ
          HUAWEICLOUD_SK: ${{ secrets.docker_secret }}

      # 部署到华为云 CAE
      - name: Deploy to CAE
        id: cli-command
        run: |
          result=$(sudo hcloud CAE ExecuteAction --cli-region=me-east-1 --project_id="00248baf96984aecac0f8a976fa7ac00" --X-Enterprise-Project-ID="0" --X-Environment-ID="811db361-727e-4b57-b247-584433244394" --application_id="8f179f8e-f914-4ae2-bbe8-c629973c7f50" --component_id="ceec9e18-211e-428f-9d38-24899085462e" --api_version='v1' --kind='Action' --metadata.name="upgrade" --metadata.annotations.version="1.0.0" --spec.source.type="image" --spec.source.url="swr.me-east-1.myhuaweicloud.com/demo-cae/cae-frontend:1.0.0")

      - name: Print CLI command result
        run: |
          echo "华为云 CLI 命令的返回结果: ${{ steps.cli-command.outputs.result }}"
